#!/bin/env bash

ramallahos-autostart &

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#Single monitor
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '0'
		
		#Dual monitor
		#find out names with arandr or xrandr
		#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
		#bspc monitor LVDS1 -d 1 2 3 4
		#bspc monitor DP3 -d  5 6 7 8 9
		#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
		#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
		#bspc monitor HDMI1 -d 1 2 3 4 5
		#bspc monitor HDMI2 -d 6 7 8 9 10
		let name++
	done
}
workspaces

bspc config border_radius                   8
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle                  false
bspc config click_to_focus                  none
bspc config split_ratio                     0.50
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config focus_by_distance               true
bspc config focus_follows_pointer           true
bspc config history_aware_focus             true
bspc config remove_disabled_monitors        true
bspc config remove_unplugged_monitors       true
bspc config automatic_scheme                alternate
bspc config initial_polarity                second_child
bspc config merge_overlapping_monitors      true
bspc config pointer_modifier                mod4
bspc config pointer_action1                 move
bspc config pointer_action2                 resize_side
bspc config pointer_action3                 resize_corner

#BSPWM coloring
bspc config focused_border_color            "#0db9d7"
bspc config active_border_color             "#c0caf5"
bspc config normal_border_color             "#acb0d0"
bspc config urgent_border_color             "#ff7a93"
bspc config presel_feedback_color           "#e0af68"
bspc config focused_locked_border_color     "#ad8ee6"
bspc config focused_sticky_border_color     "#ff9e64"
bspc config focused_private_border_color    "#b9f27c"


# workspace 1 (Terminals)
declare -a terminal=(Alacritty Xfce4-terminal konsole kitty)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(firefox discord librewolf)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Thunar Pcmanfm qBittorrent dolphin)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
declare -a office=(Code Geany emacs)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Media)
declare -a media=(vlc obs mpv mplayer lxmusic Gimp Gimp-2.10 "VirtualBox Manager")
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 7 (Settings)
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr Pavucontrol Xfce4-settings-manager)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

#fix for moving spotify to specific workspace
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command



#Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
#bspc rule -a Archlinux-tweak-tool.py state=floating
bspc rule -a Arcolinux-welcome-app.py state=floating
bspc rule -a Arcolinux-calamares-tool.py state=floating
bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
bspc rule -a Xfce4-terminal state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
