#!/bin/env bash

ramallahos-autostart &

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '0'
		let name++
	done
}
workspaces

bspc config border_radius                   8
bspc config border_width                    3
bspc config window_gap                      10
bspc config single_monocle                  false
bspc config click_to_focus                  none
bspc config split_ratio                     0.50
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config focus_by_distance               true
bspc config focus_follows_pointer           true
bspc config history_aware_focus             true
bspc config remove_disabled_monitors        true
bspc config remove_unplugged_monitors       true
bspc config automatic_scheme                alternate
bspc config initial_polarity                second_child
bspc config merge_overlapping_monitors      true
bspc config pointer_modifier                mod4
bspc config pointer_action1                 move
bspc config pointer_action2                 resize_side
bspc config pointer_action3                 resize_corner
bspc config focused_border_color            "#0db9d7"
bspc config active_border_color             "#c0caf5"
bspc config normal_border_color             "#acb0d0"
bspc config urgent_border_color             "#ff7a93"
bspc config presel_feedback_color           "#e0af68"
bspc config focused_locked_border_color     "#ad8ee6"
bspc config focused_sticky_border_color     "#ff9e64"
bspc config focused_private_border_color    "#b9f27c"


# workspace 1 (Terminals)
declare -a terminal=(Alacritty Xfce4-terminal konsole kitty)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(firefox discord librewolf)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Thunar Pcmanfm qBittorrent dolphin)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
declare -a office=(Code Geany emacs)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Media)
declare -a media=(vlc obs mpv mplayer lxmusic Gimp Gimp-2.10 "VirtualBox Manager")
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 7 (Settings)
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr Pavucontrol Xfce4-settings-manager)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done
